---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=15mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '12'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{wrapfig}
        \usepackage{enumitem}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
        \usepackage[none]{hyphenat}%%%%
---
<!-- pranav -->
\begin{huge}
  \begin{center}
    {\bf PRANAV D}
  \end{center}
\end{huge}

<!-- contct -->
\begin{center}
  \href{mailto:pranavduraisamy@outlook.com}{pranavduraisamy@outlook.com} ∙ 
  \href{https://github.com/pranavduraisamy}{Github} ∙ 
  \href{https://www.linkedin.com/in/pranavduraisamy/}{LinkedIn}
\end{center}
\vspace{5pt}

**Summary:** Mechanical engineering grad passionate about the areas of *Bayesian analysis, human body modelling and passive safety.*

<!-- EDU -->
\begin{large}{\bf EDUCATION}
  \vspace{3 pt}
  \hrule
  \vspace{3 pt}
  \setlength{\columnsep}{-10cm}
  \begin{multicols}{2}
    \begin{flushleft}
      \leftskip3pt\relax
      \textbf{Vellore Institute of Technology -- Chennai Campus}\\
      \textit{Bachelor of Technology, Mechanical Engineering with spl. in E-Vehicles}
    \end{flushleft}
      \begin{flushright}
      \rightskip3pt\relax
      Chennai, IN\\
      May 2021 - Jul 2025
    \end{flushright}
  \end{multicols}
\end{large}
\begin{large}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item CGPA: 9.44 | Gold Medallist
    \item Meritorious Award (4 consecutive years): Rank 1 {\textit{(2025, 2024)}} \& Rank 3 {\textit{(2023, 2022)}}
    \item 100\% Attendance Award recipient {\textit{(2022)}}
    \item Served as Programme Representative \& Student Council Member
  \end{itemize}
\end{large}
\vspace{7pt}

<!-- EXP -->
\begin{large}{\bf EXPERIENCE}
  \vspace{3 pt}
  \hrule

% EXP0
  \vspace{3 pt}
  \setlength{\columnsep}{-10cm}
  \begin{multicols}{2}
    \begin{flushleft}
      \leftskip3pt\relax
      \textbf{Indian Institute of Technology Madras}\\
      \textit{Project Associate}
    \end{flushleft}
    \begin{flushright}
    \rightskip3pt\relax
    Chennai, IN\\
    Jul 2025 - Present
    \end{flushright}
  \end{multicols}
\end{large}
\begin{large}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Building a robust standalone python framework to compute the deformed shape of slender rods under complex loading conditions.
    \item Employed mathematical formulations from CAD and Cosserat rod theory to simulate the behaviour of these slender structures.
  \end{itemize}

% EXP1
  \vspace{3 pt}
  \setlength{\columnsep}{-10cm}
  \begin{multicols}{2}
    \begin{flushleft}
      \leftskip3pt\relax
      \textbf{VIT -- Medical College of Wisconsin, US Joint Internship Program}\\
      \textit{Student Intern}
    \end{flushleft}
    \begin{flushright}
    \rightskip3pt\relax
    Remote\\
    Aug 2023 - Dec 2023
    \end{flushright}
  \end{multicols}
\end{large}
\begin{large}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Developed a {\textit{Smooth Particle Hydrodynamics (SPH)}} model to simulate cervical spinal cord behaviour for precise clinical interventions.
    \item Validated results against primary metrics such as segmental rotation, disc pressure and ligament strain.
  \end{itemize}

% EXP2
  \vspace{3 pt}
  \setlength{\columnsep}{-10cm}
  \begin{multicols}{2}
    \begin{flushleft}
      \leftskip3pt\relax
      \textbf{La Dassault Systèmes Foundation -- India}\\
      \textit{Engineering DESIGN Internship Program}
    \end{flushleft}
    \begin{flushright}
      \rightskip3pt\relax
      Remote\\
      May 2024 - May 2025
    \end{flushright}
  \end{multicols}
\end{large}
\begin{large}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Completed a 3-phase campus internship programme focused on the project {\textit{“Converting ‘FE model of cervical spine’ to 3D Digital bio-twin”}}.
    \item Integrated concepts from biomechanics, FEA and 3D printing in the project workflow.
  \end{itemize}
\end{large}
\vspace{7pt}

<!-- skills -->
\begin{large}{\bf CORE COMPETENCIES}
  \vspace{3 pt}
  \hrule
  \vspace{3 pt}
	\raggedcolumns
  \setlength{\columnsep}{-0.00cm}
  \begin{multicols}{3}
  \leftskip3pt\relax
			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=5pt]
					\item Bayesian Analysis
					\item Exploratory Data Analysis
				\end{itemize}
			\end{flushleft}

			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=5pt]
					\item Probabilistic Programming
					\item Spine Biomechanics
				\end{itemize}
			\end{flushleft}

			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=0.5cm]
					\item Finite Element Analysis
					\item Computer Aided Design
				\end{itemize}
			\end{flushleft}
	\end{multicols}
\end{large}
\vspace{7 pt}


<!-- pjt -->

\begin{large}
{\bf SELECTED PROJECTS}
  \vspace{3pt}
  \hrule
  \leftskip3pt\relax

%pjt1
  \textbf{Comparison of Flexion-Extension Responses between Male and Female Cervical Spine Segments}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Modelled the segmental rotations of sub-axial cervical spine segments using \textit{hierarchical Bayesian regression analysis}.
    \item Presented in IRCOBI Europe (2025) Conference, Vilnius, Lithuania.
    \item Received travel grant from Toyota, and Best Presentation in the \textit{Spine Biomechanics and Injury} session.
  \end{itemize}

% pjt2
  \textbf{Sensitivity analysis of a morphological finite element L3-L4 FSU}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Parameterized the L3-L4 FSU FE model for population study to simulate the anatomical variances using \textit{ANSA, python and LS-Dyna}.
    \item Estimated the rotation angle from anatomical parameters using \textit{Bayesian multiple linear regression}.
    \item Presented at IRCOBI Asia (2025) Conference, Chennai, India.
  \end{itemize}

\newpage

% pjt3
  \textbf{Computational Modelling of Li-ion Battery in LS-Dyna for crash applications}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Coupled mechanical, thermal and electrochemical solvers to simulate the impact and short-circuit scenarios of lithium-ion battery.
    \item Followed the Tshell elements with Randles equivalent circuit modelling approach.
  \end{itemize}

% pjt4
  \textbf{Contribution to Bambi Example Gallery}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Refined the documentation to clarify Bayesian hierarchical modelling concepts and improve consistency between Bambi and PyMC implementations.
    \item Expanded the hierarchical linear regression example by including mathematical formulations, EDA, and posterior visualisations.
  \end{itemize}

% pjt5
  \textbf{Analysis of Road Accident Fatalities in India \begin{small}\textit{(WIP)}\end{small}}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Analysing the trends in traffic accidents and fatalities classified by road, vehicles and time of occurrence.
    \item Developing a interactive data visualization dashboard to present key insights and temporal trends.
  \end{itemize}

% pjt6
  \textbf{Effect of Helmet Fit \& Orientation in Frontal and Lateral Impact \begin{small}\textit{(WIP)}\end{small}}
  \vspace{-0.2cm}
  \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
    \rightskip9pt\relax
    \item Studying the common misuse of helmets and analysing its effect on injury using finite element analysis.
    \item Identifying the most vulnerable orientation of the helmet using Bayesian analysis.
  \end{itemize}
\end{large}
\vspace{7pt}

<!-- tools -->
\begin{large}{\bf TOOLS \& SOFTWARE}
  \vspace{3 pt}
  \hrule
  \vspace{-1 pt}
	\raggedcolumns
  \setlength{\columnsep}{-0.00cm}
  {\bf {\textit{CAE Software~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Coding~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Essentials}}}
  \begin{multicols}{4}
  \leftskip3pt\relax
      
			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=5pt]
					\item ANSA pre-processor
					\item Solidworks
				\end{itemize}
			\end{flushleft}

			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=5pt]
					\item LS-Dyna
					\item Hypermesh
				\end{itemize}
			\end{flushleft}

			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=0.75cm]
					\item Python
					\item Git
				\end{itemize}
			\end{flushleft}

			\begin{flushleft}
				\vspace{-4 pt}
				\begin{itemize}[noitemsep, topsep=0pt, left=0.5cm]
					\item MS-Office
					\item Quarto
				\end{itemize}
			\end{flushleft}
	\end{multicols}
\end{large}
\vspace{7 pt}

<!-- cert -->

\begin{large}
{\bf WORKSHOPS \& CERTIFICATIONS}
  \vspace{3pt}
  \hrule
  \vspace{3pt}
  \setlength{\columnsep}{-10cm}
  \begin{multicols}{2}
    \leftskip3pt\relax
    \begin{flushleft}
      \begin{itemize}[noitemsep, topsep=0pt, left=10pt]
        \item Injury Biomechanics for Road Safety \begin{small}\textit{CODE, IITM}\end{small}
        \item An Introduction to Injury Assessment using Human Body Models \begin{small}\textit{CODE, IITM}\end{small}
        \item Introduction to Vehicle Occupant Safety \begin{small}\textit{CODE, IITM}\end{small}
        \item HyperWorks Introduction v2022 \begin{small}\textit{Altair Learning -- Online}\end{small}
        \item Python 3.4.3 Training \begin{small}\textit{Spoken Tutorial Project, IITB}\end{small}
      \end{itemize}
    \end{flushleft}
    \begin{flushright}
      \begin{small}(5D) \end{small}Jun 2025\\
      \begin{small}(2D) \end{small}Jan 2025\\
      \begin{small}(5D) \end{small}Sep 2024\\
      Jan 2023\\
      Feb 2022\\
    \end{flushright}
  \end{multicols}
\end{large}
\vspace{7pt}

<!-- extracurr -->
<!-- \begin{large} -->
<!-- {\bf VOLUNTEERING EXPERIENCE} -->
<!-- \vspace{3pt} -->
<!-- \hrule -->
<!-- \vspace{3pt} -->
<!-- \setlength{\columnsep}{-13cm} -->
<!-- \begin{multicols}{2} -->
<!-- \leftskip3pt\relax -->
<!-- \begin{flushleft} -->
<!-- \begin{itemize}[noitemsep, topsep=0pt, left=10pt] -->
<!-- \item IRCOBI Asia 2025 Conference -->
<!-- \item Nasha Mukt Bharat Abhiyan | Anti-Drug Campaign -->
<!-- \item Unnat Bharat Abhiyan | Rural Development -->
<!-- \end{itemize} -->
<!-- \end{flushleft} -->
<!-- \begin{flushright} -->
<!-- Jun 2025\\ -->
<!-- Mar 2023\\ -->
<!-- Feb 2023\\ -->
<!-- \end{flushright} -->
<!-- \end{multicols} -->
<!-- \end{large}  -->
<!-- ref -->

\begin{large}
{\bf REFERENCE}
  \vspace{3pt}
  \hrule
  \leftskip3pt\relax
  \textbf{Jobin John}\\
    \rightskip9pt\relax
    Researcher, Vehicle Safety, Mechanics and Maritime Sciences\\
    Chalmers University of Technology - Gothenburg, SE\\
    \href{mailto:jobin.john@chalmers.se}{jobin.john@chalmers.se}\\
    \href{tel:+46-31-772-65-97}{+46-31-772-65-97}
\end{large}

\vfill
\begin{flushright}
  \begin{small}
    \textit{*Last updated on \today}
  \end{small}
\end{flushright}